config/routes.rb
Rails.application.routes.draw do
 
  match "signup", :to => "users#new", via: [:get]
  match "login", :to => "sessions#login", via: [:get]
  match "login_attempt", :to => "sessions#login_attempt", via: [:post]
  match "logout", :to => "sessions#logout", via: [:get]
  match "profile", :to => "sessions#profile", via: [:get]
  match "setting", :to => "sessions#setting", via: [:get]

  match "arts/new", :to => "arts#new", via: [:get]
  match "arts/create", :to => "arts#create", via: [:post]
  match "arts/:params", :to => "arts#admin", via: [:get]
  resources :arts
  resources :users
  root 'arts#index'

end

app/models/art.rb
require 'simple_enum'

class Art < ActiveRecord::Base
	as_enum :category, studies: 0, themes: 1, drawings: 2
	validates :title, presence: true, length: { in: 4...50 }
  validates_presence_of :description
  validates_presence_of :medium
  validates :category_cd, presence: true, :inclusion => { :in => 0..2 }
  validates :year, presence: true, :inclusion => { :in => 2010..Date.today.year }
  validates :width, presence: true, :inclusion => { :in => 10..200 }
  validates :height, presence: true, :inclusion => { :in => 10..200 }
  validates_presence_of :user_id
  mount_uploader :filename, ImageUploader
  validates_presence_of :filename
  belongs_to :user

  def self.find_all_by_category(category)
    Art.where(:category_cd=>Art.categories[category]).all
  end
end

app/models/article.rb
require 'simple_enum'

class Article < ActiveRecord::Base
	as_enum :category, studies: 0, themes: 1, drawings: 2
	validates :title, presence: true, length: { in: 10...50 }
  validates :description, presence: true
  validates :medium, presence: true
  validates :category_cd, presence: true, :inclusion => { :in => 0..2 }
  validates :year, presence: true, :inclusion => { :in => 2010..Date.today.year }
  validates :width, presence: true, :inclusion => { :in => 10..200 }
  validates :height, presence: true, :inclusion => { :in => 10..200 }
  validates :filename, presence: true

	def process_uploaded_file(file)
		name =  file.original_filename
		directory = File.join(Rails.root, ENV["UPLOADED_FILE_PATH"])
		# create the file path
		path = File.join(directory, name)
		# write the file
		File.open(path, "wb") { |f| f.write(file.read) }
		self.filename = path
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  EMAIL_REGEX = /\S[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
  validates :email,
    :presence => true,
    :uniqueness => true,
    :format => {
      with: EMAIL_REGEX,
      message: 'Please enter a valid email address'
    }
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create

  before_save :encrypt_password
  after_save :clear_password
  has_many :arts

  def self.authenticate(email="", login_password="")
    if EMAIL_REGEX.match(email)
      user = User.find_by_email(email)
    end

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user

  protected 
  def authenticate_user
    if session[:user_id]
      # set current user object to @current_user object variable
      @current_user = User.find session[:user_id] 
    end
  end

  def authenticate_user_and_redirect
    if session[:user_id]
      # set current user object to @current_user object variable
      @current_user = User.find session[:user_id] 
      return true 
    else
      redirect_to(:controller => 'sessions', :action => 'login')
      return false
    end
  end

  def save_login_state
    if session[:user_id]
      redirect_to(:controller => 'arts', :action => 'index')
    end
  end
end

app/controllers/arts_controller.rb
require 'arts_service'

class ArtsController < ApplicationController
	before_filter :store_prev_url, :only => [:index, :admin, :destroy]
	before_filter :authenticate_user_and_redirect, :only => [:new, :create, :destroy]
	before_filter :authenticate_user, :only => [:index, :show, :edit]

	def new
	end

	def destroy
		ArtsService.destroy(params[:id])
		redirect_to session.delete(:return_to)
	end	

	def create
		ArtsService.create(art_params, @current_user)
	end

	def update
  		if ArtsService.update(params[:id], art_params)
	  		redirect_to session.delete(:return_to)
  		else
	  		render 'edit'
		end
	end

	def edit
		@art = Art.find(params[:id])
	end

	def index
		@arts = ArtsService.get_arts
		respond_to do |format|
			format.html
			format.json { render json: @arts }
		end
	end

	def show
	  	@art = Art.find(params[:id])
	end

	def admin
		if authenticate_user
			@arts = Art.find_all_by_category(params[:params])
		else
			redirect_to(:controller => 'sessions', :action => 'login')
		end
	end

	private

	def art_params
		params.require(:art).permit(:title, :description, :category_cd, :width, :height, :filename, :medium, :year)
	end

	def store_prev_url
		session[:return_to] ||= request.referer
		if session[:return_to] != request.referer
			session[:return_to] = request.referer
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authenticate_user_and_redirect, :only => [:profile, :setting]
  before_filter :save_login_state, :only => [:login, :login_attempt]

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  def login
  end

  def login_attempt
    authorized_user = User.authenticate(params[:username_or_email], params[:login_password])
    if authorized_user
      session[:user_id] = authorized_user.id
      redirect_to root_path
      flash[:notice] = "You logged in as #{authorized_user.email}"
    else
      redirect_to(:controller => 'sessions', :action => 'login')
      flash[:danger] = "Wrong username or password"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :save_login_state, :only => [:new, :create]

  def new
    if Rails.env.production?
      redirect_to root_path
      flash[:danger] = "Sign up is not available on production!"
    end
  end

  def create
    if Rails.env.production?
      redirect_to root_path
      flash[:danger] = "Sign up is not available on production!"
    else
      @user = User.new(user_params)
      if @user.save!
        session[:user_id] = @user.id
        redirect_to root_path
        flash[:notice] = "You signed up successfully"
      else
        flash[:danger] = "Failed to sign up"
        render "new"
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :medium %><br>
    <%= f.text_field :medium %>
  </p>
 
  <p>
    <%= f.label :category %><br>
    <%= select :article, :category_cd, enum_option_pairs(Article, :category, true) %>
  </p>

  <p>
    <%= f.label :width %><br>
    <%= f.select :width, options_for_select(10..100)%>
  </p>

  <p>
    <%= f.label :height %><br>
    <%= f.select :height, options_for_select(10..100)%>
  </p>

  <p>
    <%= f.label :year %><br>
    <%= f.select :year, options_for_select(2010..Date.today.year)%>
  </p>

  <p>
    <%= f.label :file %><br>
    <%= f.file_field :filename %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>medium:</strong>
  <%= @article.medium %>
</p>

<p>
  <strong>year:</strong>
  <%= @article.year %>
</p>

<p>
  <strong>size:</strong>
  <%= @article.width %> by <%= @article.height %>
</p>

<p>
  <strong>category:</strong>
  <%= @article.category %>
</p>

<p>
  <strong>filename:</strong>
  <%= @article.filename %>
</p>

app/views/arts/_new.html.erb
<%= form_for :art, :html => {:multipart => true}, url: @path do |f| %>
  <div class="form-group">
    <%= f.label :title, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class=>"form-control", :maxlength => 30, :size => 30 %>
    </div>
  </div>
 
  <div class="form-group">
    <%= f.label :description, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :class=>"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :medium, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :medium, :class=>"form-control" %>
    </div>
  </div>
 
  <div class="form-group">
    <label class="col-sm-2 control-label" for="art_category">Category</label>
    <div class="col-sm-10">
      <select class="form-control" id="art_category_cd" name="art[category_cd]">
      	<option value="0">Studies</option>
      	<option value="1">Themes</option>
      	<option value="2">Drawings</option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :width, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:width, options_for_select(10..100), {}, {:class=>"form-control"})%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :height, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:height, options_for_select(10..100), {}, {:class=>"form-control"})%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :year, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:year, options_for_select(2010..Date.today.year), {}, {:class=>"form-control"})%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :file, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :filename, :class=>"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", :class=>'btn btn-primary' %>
  </div>
<% end %>

app/views/arts/admin.html.erb
<%=link_to "new", new_art_path, :class=>'btn btn-default' %>
<div class="row-fluid">
<% @arts.each do |art| %>
  <div class="col-xs-4 col-sm-3 col-md-2">
    <div class="imageContainer">
        <a href="<%=config.relative_url_root%><%=art.filename_url.to_s%>" data-lightbox="arts"
           data-title="<%=art.title%>, <%=art.width%>x<%=art.height%>, <%=art.medium%>, <%=art.year%>">
          <%=image_tag art.filename_url(:thumb).to_s, :class=>'art' %>
        </a>
        <%=link_to "edit", edit_art_path(art), :class=>'btn btn-primary' %> |
        <%=link_to "delete", art_path(art.id), :method => :delete, :class=>'btn btn-danger' %>
    </div>
  </div>
<% end %>
</div>

app/views/arts/create.html.erb
<script language = "javascript">
window.location.href="/arts/" + "<%=@art.category.to_s%>";
</script>

app/views/arts/edit.html.erb
<h2>Edit</h2>
<%= form_for @art do |f| %>
  <input hidden name="id" value="<%=@art.id%>">
  <div class="form-group">
    <%= f.label :title, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class=>"form-control", :maxlength => 30, :size => 30 %>
    </div>
  </div>
 
  <div class="form-group">
    <%= f.label :description, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :class=>"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :medium, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :medium, :class=>"form-control" %>
    </div>
  </div>
 
  <div class="form-group">
    <label class="col-sm-2 control-label" for="art_category">Category</label>
    <div class="col-sm-10">
      <select class="form-control" id="art_category_cd" name="art[category_cd]">
        <option value="0">Studies</option>
        <option value="1">Themes</option>
        <option value="2">Drawings</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :width, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:width, options_for_select(10..100), {}, {:class=>"form-control"})%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :height, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:height, options_for_select(10..100), {}, {:class=>"form-control"})%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :year, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:year, options_for_select(2010..Date.today.year), {}, {:class=>"form-control"})%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :file, :class=>"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :filename, :class=>"form-control" %>
    </div>
  </div>


  <div class="form-group">
    <%= f.submit "Update", :class=>'btn btn-primary' %>
  </div>

<% end %>

app/views/arts/index.html.erb
<script language = "javascript">
if(window.location.hash=="") {
  window.location.hash="/#"
}
</script>

app/views/arts/new.html.erb
<%=
@path = arts_create_path
render :partial => "arts/new"
%>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html ng-app="gallery">
<head>
  <title>Hyunju Kim</title>
  <script type="text/javascript" language="JavaScript">
    // site prefix
    window.sitePrefix = "<%=config.relative_url_root%>";
  </script>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <base href="/" />
  <meta name="viewport" content="user-scalable=no, width=device-width, minimum-scale=1, maximum-scale=1">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Petrona" />
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Signika" />
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Finger+Paint" />
</head>

<body ng-controller="MenuController">

<%= render 'layouts/messages' %>

<div class="navbar navbar-default navbar-top" role="navigation">
  <div class="container navbar-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="title" ui-sref="home">HYUNJU KIM</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user %>
          <li class=<%= "active" if params[:params] == "studies"%>><a href="<%=config.relative_url_root%>/arts/studies" class = "links">studies</a></li>
          <li class=<%= "active" if params[:params] == "themes"%>><a href="<%=config.relative_url_root%>/arts/themes" class = "links">themes</a></li>
          <li class=<%= "active" if params[:params] == "drawings"%>><a href="<%=config.relative_url_root%>/arts/drawings" class = "links">drawings</a></li>
        <% else %>
          <li ng-class="{ active: $state.includes('studies') }"><a ui-sref="studies" class = "links">studies</a></li>
          <li ng-class="{ active: $state.includes('themes') }"><a ui-sref="themes" class = "links">themes</a></li>
          <li ng-class="{ active: $state.includes('drawings') }"><a ui-sref="drawings"  class = "links">drawings</a></li>
        <% end %>

        <li ng-class="{ active: $state.includes('artist_info') }"><a ui-sref="artist_info" class = "links">artist info</a></li>
        <% if @current_user %>
          <li><a href = "#" class = "links"><%=@current_user.email%> profile</a></li>
          <li><a href = "<%=config.relative_url_root%>/logout" class = "links">logout</a></li>
        <% end %>        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.navbar-container -->
  <div class="container">
    <div ui-view autoscroll="false" style="margin-left:50px; margin-right:50px"></div>
    <%=yield%>
  </div> <!-- /container -->
</div>

<div id="share"></div>

<script type="text/javascript" language="JavaScript">
$(document).ready(function () {
    $('#share').share({
        networks: ['facebook','pinterest','googleplus','twitter','linkedin','tumblr','email','stumbleupon'],
        orientation: 'vertical',
        urlToShare: 'http://www.whyi.net/hyunju',
        affix: 'right center'
    });
});
</script>
  
<div class="footer" align="center">
    &copy; 2014 / All rights reserved by Hyunju Kim 
</div>


</body>

</html>

app/views/users/new.html.erb
<% @page_title = "Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>

    <div class="row">
      <div class="form-group col-lg-2">
        <%= label_tag 'Email' %>
      </div>
      <div class="form-group col-lg-2">
        <%= f.text_field :email, :class => 'form-control' %></p>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-lg-2">
        <%= label_tag 'Password' %>
      </div>
      <div class="form-group col-lg-2">
        <%= f.password_field :password, :class => 'form-control' %></p>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-lg-2">
        <%= label_tag 'Password Confirmation' %>
      </div>
      <div class="form-group col-lg-2">
        <%= f.password_field :password_confirmation, :class => 'form-control' %></p>
      </div>
    </div>
    <%= f.submit :Signup, :class=>'btn btn-default' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<h1>Hello, Rails!</h1>